### ISSUE TITLE
Using the same id for SVG elements causes bug when selectively hiding avatars

### ISSUE THREAD

**Issue by justuswilhelm** [paolotiu/svelte-boring-avatars#1]
Hi, first of all thanks for creating this library. It's very easy to get started with and the design has a certain "wow" factor :)

Now, I selectively hide some elements that contain boring avatars. The fact that ids used for some of the svg elements means that SVGs further down the DOM do not get rendered correctly. A small example can be found here: https://svelte.dev/repl/4b4b5ebcc88c4dc1bbc2a6c924f86a1d?version=3.42.4 (thanks for the REPL link in the README!)

Apparently this is a [well known](https://stackoverflow.com/questions/72871578/visibility-hidden-svg-sibling-side-effect) issue/spec misunderstanding with SVG. I had this before when embedding SVGs as svelte components instead of img tags. The solution is to make IDs unique.

I briefly looked at the code in this repository and it seems to fairly easy to patch each component to emit unique ids.

**Comment by paolotiu** [comment]
Fixed by #2

**Comment by paolotiu** [comment]
Fixed by #2

**Comment by paolotiu** [comment]
Fixed in version 1.2.3
