### ISSUE TITLE
Please add an OSS license

### ISSUE THREAD

**Issue by justuswilhelm** [paolotiu/svelte-boring-avatars#3]
Hi @paolotiu 

Thanks again for merging my PR from last time. Would you think it is possible to license this code under a OSS (i.e., [open source definition](https://opensource.org/osd/)) license? I am using this wonderful library in my project "Projectify" (frontend repo [here])https://github.com/jwp-consulting/projectify-frontend)) which itself is licensed under AGPLv3.

Since Projectify is a project management application, users can post task cards etc here. The task cards have boring avatars as a fallback for users who did not upload a profile picture, as can be seen on this screenshot.

<img width="448" alt="task card projectify" src="https://github.com/paolotiu/svelte-boring-avatars/assets/1641042/a29f8612-5087-467c-8b52-b5c2e7016a5e">

It would be tremendously valuable to have this library available licensed freely.

Best,
Justus

**Comment by paolotiu** [comment]
Added an MIT License!

**Comment by justuswilhelm** [comment]
Sweet!
